#!/usr/bin/env php
<?php

use Illuminate\Console\Application;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap the Laravel application...
(require_once __DIR__.'/bootstrap/app.php')
    ->handleCommand(new Application);
