import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link } from '@inertiajs/react';
export default function CompanyDashboard({ recentServices }) {
    return (_jsxs(AuthenticatedLayout, { header: _jsx("h2", { className: "font-semibold text-xl text-gray-800 leading-tight", children: "Painel da Empresa" }), children: [_jsx(Head, { title: "Dashboard" }), _jsx("div", { className: "py-12", children: _jsxs("div", { className: "max-w-7xl mx-auto sm:px-6 lg:px-8", children: [_jsx("div", { className: "flex justify-end mb-4", children: _jsx(Link, { href: route('services.create'), className: "bg-primary text-white px-4 py-2 rounded-md hover:bg-blue-700", children: "Novo Servi\u00E7o" }) }), _jsx("div", { className: "bg-white overflow-hidden shadow-sm sm:rounded-lg", children: _jsxs("div", { className: "p-6", children: [_jsx("h3", { className: "text-lg font-medium text-gray-900 mb-4", children: "Servi\u00E7os Recentes" }), _jsx("div", { className: "overflow-x-auto", children: _jsxs("table", { className: "min-w-full divide-y divide-gray-200", children: [_jsx("thead", { className: "bg-gray-50", children: _jsxs("tr", { children: [_jsx("th", { className: "px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider", children: "T\u00EDtulo" }), _jsx("th", { className: "px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider", children: "Data" }), _jsx("th", { className: "px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider", children: "Montador" }), _jsx("th", { className: "px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider", children: "Status" })] }) }), _jsx("tbody", { className: "bg-white divide-y divide-gray-200", children: recentServices.map((service) => (_jsxs("tr", { children: [_jsx("td", { className: "px-6 py-4 whitespace-nowrap", children: service.title }), _jsx("td", { className: "px-6 py-4 whitespace-nowrap", children: new Date(service.scheduled_at).toLocaleDateString() }), _jsx("td", { className: "px-6 py-4 whitespace-nowrap", children: service.montador ? service.montador.name : '-' }), _jsx("td", { className: "px-6 py-4 whitespace-nowrap", children: _jsx("span", { className: `px-2 inline-flex text-xs leading-5 font-semibold rounded-full 
                                                        ${service.status === 'open' ? 'bg-yellow-100 text-yellow-800' :
                                                                        service.status === 'accepted' ? 'bg-blue-100 text-blue-800' :
                                                                            'bg-green-100 text-green-800'}`, children: service.status }) })] }, service.id))) })] }) })] }) })] }) })] }));
}
//# sourceMappingURL=Company.js.map